### ISSUE TITLE
Too many input arguments？

### ISSUE THREAD

**Issue by shuangsw** [HybridRobotics/CBF-CLF-Helper#6]
When I run the 2DDI case, MATLAB says" Error using DoubleIntegrator2D \\ too many  input arguments".

**Comment by Oghentega** [comment]
When I run the ACC case, MATLAB says;
 "Undefined function or variable 'ACC'.

Error in run_cbf_clf_simulation_acc (line 33)
accSys = ACC(params); "

Please, see the attached screenshot for details of the error message. 
PS: It gave me a similar error also for the other case. Am using MATLAB R2019a.

![SharedScreenshot](https://user-images.githubusercontent.com/106090814/170258910-3a6f7895-1ce6-4944-81cb-139f00376541.jpg)

Thanks.

**Comment by tinytinywell** [comment]
> When I run the ACC case, MATLAB says; "Undefined function or variable 'ACC'.
> 
> Error in run_cbf_clf_simulation_acc (line 33) accSys = ACC(params); "
> 
> Please, see the attached screenshot for details of the error message. PS: It gave me a similar error also for the other case. Am using MATLAB R2019a.
> 
> ![SharedScreenshot](https://user-images.githubusercontent.com/106090814/170258910-3a6f7895-1ce6-4944-81cb-139f00376541.jpg)
> 
> Thanks.

Hello, I have this problem too, have you figured out why this error occurs?

**Comment by ChoiJangho** [comment]
@tinytinywell Please add the main directory of the library and all the subdirectories to the Matlab path before running the script. You can do this by typing: addpath(genpath("YOURROOTPATHNAME")) in the matlab command window where your root path name is something like C:/Username/cbf_clf_helper. Please let me know if this fixed the error.

**Comment by tinytinywell** [comment]
> @tinytinywell Please add the main directory of the library and all the subdirectories to the Matlab path before running the script. You can do this by typing: addpath(genpath("YOURROOTPATHNAME")) in the matlab command window where your root path name is something like C:/Username/cbf_clf_helper. Please let me know if this fixed the error.

It works, thank you very much!!
