### ISSUE TITLE
Unrecognized method, property, or field 'initSys' for class 'ACC'.

### ISSUE THREAD

**Issue by kalebbennaveed** [HybridRobotics/CBF-CLF-Helper#8]
Not entirely sure what is causing this error

**Comment by kalebbennaveed** [comment]
It is resolved

**Comment by inshaandrabi** [comment]
how did you resolve this issue, I am facing the same problem

**Comment by cyye403** [comment]
> how did you resolve this issue, I am facing the same problem

Hi, did you solve the problem? If not, I think this reply will help you:

**Comment by cyye403** [comment]
> how did you resolve this issue, I am facing the same problem

Hi, did you solve the problem? If still not, I think my comment here will help you:

At first, i met the same problem as you do 'cause i just ignored the tips in "Usage", which said class functions "definesystem", "defineClf" and "defineCbf" are to be createrd. Noticing this, i 
    1) add dir dynsys and lib to Matlab path,
    2) copied the contents in the three m function under @ACC to the corresponding class functions in CtrlAffineSys.m, and
    3) add another class function "ctrlCbfClfQp" to CtrlAffineSys class, while copying "ctrlCbfClfQp.m" under lib/@CtrlAffineSys here.
Then i found this problem solved, hope this works for u too(*￣︶￣). 

By the way, lane keeping simulation demo is not included in the project, would you tell me where i can find one for anyone who notice this comment?

**Comment by cyye403** [comment]
> Hi, did you solve the problem? If still not, I think my comment here will help you:
> 
> At first, i met the same problem as you do 'cause i just ignored the tips in "Usage", which said class functions "definesystem", "defineClf" and "defineCbf" are to be createrd. Noticing this, i 1) add dir dynsys and lib to Matlab path, 2) copied the contents in the three m function under @acc to the corresponding class functions in CtrlAffineSys.m, and 3) add another class function "ctrlCbfClfQp" to CtrlAffineSys class, while copying "ctrlCbfClfQp.m" under lib/@CtrlAffineSys here. Then i found this problem solved, hope this works for u too(*￣︶￣).
> 
> By the way, lane keeping simulation demo is not included in the project, would you tell me where i can find one for anyone who notice this comment?

Hi, did you solve the problem? If still not, I think my comment here will help you:

At first, i met the same problem as you do 'cause i just ignored the tips in "Usage", which said class functions "definesystem", "defineClf" and "defineCbf" are to be createrd. Noticing this, i
1) add dir dynsys and lib to Matlab path,
2) copied the contents in the three m function under @ACC to the corresponding class functions in CtrlAffineSys.m, and
3) add another class function "ctrlCbfClfQp" to CtrlAffineSys class, while copying "ctrlCbfClfQp.m" under lib/@CtrlAffineSys here.
Then i found this problem solved, hope this works for u too(*￣︶￣).

By the way, lane keeping simulation demo is not included in the project, would you tell me where i can find one for anyone who notice this comment?

**Comment by cyye403** [comment]
> how did you resolve this issue, I am facing the same problem

Hi, did you solve the problem? If still not, I think my comment here will help you:

At first, i met the same problem as you do 'cause i just ignored the tips in "Usage", which said class functions "definesystem", "defineClf" and "defineCbf" are to be createrd. Noticing this, i

add dir dynsys and lib to Matlab path,
copied the contents in the three m function under @ACC to the corresponding class functions in CtrlAffineSys.m, and
add another class function "ctrlCbfClfQp" to CtrlAffineSys class, while copying "ctrlCbfClfQp.m" under lib/@CtrlAffineSys here.
Then i found this problem solved, hope this works for u too(*￣︶￣).
By the way, lane keeping simulation demo is not included in the project, would you tell me where i can find one for anyone who notice this comment?

**Comment by cyye403** [comment]
> how did you resolve this issue, I am facing the same problem

Hi, did you solve the problem? If still not, I think my comment here will help you:

At first, i met the same problem as you do 'cause i just ignored the tips in "Usage", which said class functions "definesystem", "defineClf" and "defineCbf" are to be createrd. Noticing this, i \\

1) add dir dynsys and lib to Matlab path,
2) copied the contents in the three m function under "@ACC" to the corresponding class functions in CtrlAffineSys.m, and
3) add another class function "ctrlCbfClfQp" to CtrlAffineSys class, while copying "ctrlCbfClfQp.m" under "lib/@CtrlAffineSys" here.

Then i found this problem solved, hope this works for u too(*￣︶￣). \\

By the way, lane keeping simulation demo is not included in the project, would you tell me where i can find one for anyone who notice this comment?
