### ISSUE TITLE
Question about 2 relative degree example

### ISSUE THREAD

**Issue by rlsotlr01** [HybridRobotics/CBF-CLF-Helper#9]
--

**Comment by ChoiJangho** [comment]
Hi, thank you for your question, these [two lines](https://github.com/HybridRobotics/CBF-CLF-Helper/blob/956c88bb1ed72b76feffd882df7e491893391c77/dynsys/%40DoubleIntegrator2D/DoubleIntegrator2D.m#L22-L23) implement exponential CBF (High-order CBF) of relative degree two by adding a derivative term to the CBF: 
This is an indirect implementation of the high-order CBF but you can do this for higher relative degree as well.
